#!/bin/bash
#
# behilarious
#
# Jon Simons
# June 14, 2012

N="terminal-notifier"
while [ 1 ]
do
  ${N} -message "$($(dirname $0)/getRandomWiki)" -title "HILARIOUS"
  echo "sleeping"
  date
  sleep 5s
done
