#!/bin/bash
#
# behilarious
#
# Jon Simons
# June 14, 2012
while [ 1 ]; do notify-send "HILARIOUS" "`./getRandomWiki | html2text -nobs | tail -n +2 | tr '\n' ' '`"; echo "sleeping"; date; sleep 5s; done
