#!/bin/bash
#
# behilarious
#
# Jon Simons
# June 14, 2012

N="terminal-notifier"
TITLE="-title HILARIOUS"
TAIL="tail"
TR="tr"
HTML2TEXT="html2text"
while [ 1 ]
do
  TXT="`./getRandomWiki | $HTML2TEXT -nobs | $TAIL -n +2 | $TR '\n' ' '`"
  ${N} -message "${TXT}" -title "HILARIOUS"
  echo "sleeping"
  date
  sleep 5s
done
