#!/bin/bash
#
# Fetches a random English Wikipedia article, strips out its title and
# first <p>...</p>, and seds its links to be absolute ones instead of
# relative ones.

E="/bin/echo"

curl -L http://en.wikipedia.org/wiki/Special:Random 2>/dev/null \
  | grep -E "<(p|title)>" \
  | grep -E "<(b|title)>" \
  | head -n 2 \
  | sed 's?.*<title>\(.*\) - .*</title>?\1?g' \
  | sed 's?.*<p>?<p>?g' \
  | sed 's?a href="/wiki?a href="http://en.wikipedia.org/wiki?g'
